# Generated by Django 4.1.2 on 2022-10-09 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(default=uuid.uuid4)),
                ('brand', models.CharField(max_length=64)),
                ('brand_version', models.CharField(max_length=16)),
                ('architecture', models.CharField(max_length=4)),
                ('model', models.CharField(max_length=32)),
                ('platform', models.CharField(max_length=32)),
                ('platform_version', models.CharField(max_length=16)),
                ('is_mobile', models.BooleanField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
