# Generated by Django 4.1.2 on 2022-10-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='architecture',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='brand',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='brand_version',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='is_mobile',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='model',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='platform_version',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
