# Generated by Django 4.1.2 on 2022-10-09 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('devices', '0002_alter_device_architecture_alter_device_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=12)),
                ('altitude', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('altitude_accuracy', models.FloatField(null=True)),
                ('heading', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('timestamp', models.BigIntegerField(null=True)),
                ('logged_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.device')),
            ],
        ),
    ]
