# Generated by Django 4.0.6 on 2022-07-17 16:04

import accounts.util
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='auth_code',
            field=models.CharField(default=accounts.util.make_auth_code, help_text='Email verification code', max_length=5, verbose_name='auth code'),
        ),
    ]
